version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: frankstark/todo-flask
    container_name: todo-flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
